#!/usr/bin/env python3

from sys import argv, stderr

def helper() -> None:
    """Display the prgram usage."""
    print('USAGE',
            '\t./206neutrinos n a h sd\n',
            'DESCRIPTION',
            '\tn\tnumber of values',
            '\ta\tarithmetic mean',
            '\th\tharmonic mean',
            '\tsd\tstandard deviation',
            sep='\n', end='\n')

def error(str: str) -> None:
    """Write error msg on error output then exits 84."""
    str = str + '\n'
    stderr.write(str)
    exit(84)

if __name__ == "__main__":
    data = []
    if len(argv) == 2 and argv[1] == "-h":
        helper()
    elif len(argv) != 5:
        error('invalid arguments.')
    else:
        try:
            for i in range(1, 5):
                data.append(int(argv[i]))
        except ValueError:
            error('Agruments must be integers.')
